.TH "ExceptionError" 3 "Mon Dec 27 2021" "StringUnpacker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExceptionError \- Структура пользовательское исключение  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <header\&.hpp>\fP
.PP
Inherits invalid_argument\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExceptionError\fP (const \fBTermError\fP code)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Структура пользовательское исключение 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExceptionError::ExceptionError (const \fBTermError\fP code)\fC [explicit]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for StringUnpacker from the source code\&.
