.TH "Проект/KNPO_PrIn_266_Nikolaev/StringUnpacker/header.hpp" 3 "Mon Dec 27 2021" "StringUnpacker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Проект/KNPO_PrIn_266_Nikolaev/StringUnpacker/header.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string_view>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <charconv>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBUnit\fP"
.br
.RI "Структура модуль "
.ti -1c
.RI "struct \fBExceptionError\fP"
.br
.RI "Структура пользовательское исключение "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTermError\fP { \fBTermError::Success\fP, \fBTermError::WrongSymbol\fP, \fBTermError::EndNumber\fP, \fBTermError::WrongRageOfString\fP, \fBTermError::WrongRepeat\fP }"
.br
.RI "Набор возможных ошибок программы "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBUnit\fP lhs, const \fBUnit\fP rhs)"
.br
.RI "Операция сравнения двух модулей на равенство "
.ti -1c
.RI "std::string \fBStringProcessing\fP (std::string_view str)"
.br
.RI "Распаковать строку "
.ti -1c
.RI "std::vector< \fBUnit\fP > \fBDivideStringToChars\fP (std::string_view str)"
.br
.RI "Разделить строку на модули "
.ti -1c
.RI "\fBTermError\fP \fBLateEvaluation\fP (std::string_view str)"
.br
.RI "Проверить содержимое строки на корректность "
.ti -1c
.RI "std::vector< std::string > \fBDivideString\fP (std::string_view str, int border)"
.br
.RI "Разбить распакованную строку на массив строк по заданной длине "
.ti -1c
.RI "int \fBPreExecuteCheck\fP (int argc, char **argv, std::string &str)"
.br
.RI "Проверка файла на корректность "
.ti -1c
.RI "auto \fBFillUnitArray\fP (std::string_view::const_iterator &currentIterator, const std::string_view &inputData, std::vector< \fBUnit\fP > &arrayOfCharacters)"
.br
.RI "Сформировать модуль и записать его в массив "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBTermError\fP\fC [strong]\fP"

.PP
Набор возможных ошибок программы 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISuccess \fP\fP
нет ошибки 
.TP
\fB\fIWrongSymbol \fP\fP
ошибка: неразрешенный символ в строке 
.TP
\fB\fIEndNumber \fP\fP
ошибка: в строке последний символ – цифра 
.TP
\fB\fIWrongRageOfString \fP\fP
ошибка: размер строки вне разрешенного диапазона 
.TP
\fB\fIWrongRepeat \fP\fP
ошибка: число повторений буквы вне разрешенного диапазона 
.SH "Function Documentation"
.PP 
.SS "std::vector<std::string> DivideString (const std::string_view inputData, const int border)"

.PP
Разбить распакованную строку на массив строк по заданной длине 
.PP
\fBParameters\fP
.RS 4
\fIinputData\fP распакованная строка 
.br
\fIborder\fP ограничитель длины строки
.RE
.PP
\fBReturns\fP
.RS 4
массив строк по заданной длине 
.RE
.PP
Вернуть пустой массив, если лимит меньше либо равен 0
.PP
Создать результирующий массив строк
.PP
Для каждой группы символов, длина которой равна лимиту
.PP
Создать строку из текущей группы символов
.PP
/Добавить строку в результирующий массив
.PP
Добавить группу символов в результирующий массив, если она находится конце строки и ее длина меньше лимита
.PP
Вернуть результирующий массив
.SS "std::vector<\fBUnit\fP> DivideStringToChars (const std::string_view inputData)"

.PP
Разделить строку на модули 
.PP
\fBParameters\fP
.RS 4
\fIinputData\fP входная строка
.RE
.PP
\fBReturns\fP
.RS 4
массив модулей 
.RE
.PP
Создать массив, в который будем сохранять модули
.PP
Для каждого символа строки
.PP
Если текущий символ – буква
.PP
Добавить в массив модуль с текущим символом и количеством символов равным 1
.PP
Перейти к следующей итерации
.PP
Сформировать модуль и записать его в массив
.PP
Вернуть получившийся массив модулей
.SS "auto FillUnitArray (std::string_view::const_iterator & currentIterator, const std::string_view & inputData, std::vector< \fBUnit\fP > & arrayOfCharacters)"

.PP
Сформировать модуль и записать его в массив 
.PP
\fBParameters\fP
.RS 4
\fI[in|out]\fP currentIterator ссылка на текущий символ, на котором остановился итератор 
.br
\fI[in|out]\fP inputData ссылка на текущий символ, на котором остановился итератор 
.br
\fI[in|out]\fP arrayOfCharacters ссылка на текущий символ, на котором остановился итератор
.RE
.PP
\fBReturns\fP
.RS 4
текущий символ, на котором остановился итератор 
.RE
.PP
Начало числа повторений – текущий символ
.PP
Найти первый нецифровой символ – это запоследний символ числа повторений, а также повторяемая буква
.PP
Конвертировать строку с числом повторением в число
.PP
Если число повторений не входит в разрешенный диапазон – выдать ошибку
.PP
Добавить в массив модуль с вычисленным числом повторений и повторяемой буквой
.PP
Считать текущим символом следующий символ после повторяемой буквы
.SS "\fBTermError\fP LateEvaluation (const std::string_view inputData)"

.PP
Проверить содержимое строки на корректность 
.PP
\fBParameters\fP
.RS 4
\fIinputData\fP входная строка
.RE
.PP
\fBReturns\fP
.RS 4
код ошибки 
.RE
.PP
Вернуть код ошибки типа 'некорректный символ', если найден символ, который не является заглавной латинской буквой или цифрой
.PP
Вернуть код ошибки типа 'последняя цифра', если последний символ является цифрой
.PP
Вернуть код без ошибки
.SS "bool operator== (const \fBUnit\fP lhs, const \fBUnit\fP rhs)\fC [inline]\fP"

.PP
Операция сравнения двух модулей на равенство 
.PP
\fBParameters\fP
.RS 4
\fI1hs\fP первый модуль 
.br
\fI2hs\fP второй модуль
.RE
.PP
\fBReturns\fP
.RS 4
результат операции 
.RE
.PP

.SS "int PreExecuteCheck (int argc, char ** argv, std::string & str)"

.PP
Проверка файла на корректность 
.PP
\fBParameters\fP
.RS 4
\fIargc\fP количество аргументов командной строки 
.br
\fIargv\fP аргументы командной строки 
.br
\fI[in|out]\fP str упакованная строка
.RE
.PP
\fBReturns\fP
.RS 4
код ошибки 
.RE
.PP
Если входной файл не указан в аргументах командной строки
.PP
Вывести сообщение об ошибке и завершить работу программы
.PP
Если входной файл невозможно открыть
.PP
Вывести сообщение об ошибке и завершить работу программы
.PP
Считать строку из файла
.SS "std::string StringProcessing (const std::string_view inputData)"

.PP
Распаковать строку 
.PP
\fBParameters\fP
.RS 4
\fIinputData\fP входная строка
.RE
.PP
\fBReturns\fP
.RS 4
распакованная строка 
.RE
.PP
Выдать ошибку, если размер строки не соответствует разрешенному диапазону
.PP
Выдать ошибку, если содержимое строки не корректно
.PP
Разделить строку на модули\&.\&.\&.
.PP
Перевести модули в распакованную строку\&.\&.\&.
.PP
Для каждого модуля
.PP
Вернуть распакованную строку
.SH "Author"
.PP 
Generated automatically by Doxygen for StringUnpacker from the source code\&.
