.TH "Проект/KNPO_PrIn_266_Nikolaev/StringUnpacker/StringUnpacker.vcxproj.filters.txt" 3 "Mon Dec 27 2021" "StringUnpacker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Проект/KNPO_PrIn_266_Nikolaev/StringUnpacker/StringUnpacker.vcxproj.filters.txt
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "<?xml version='1\&.0' encoding='utf\-8'?>< Project ToolsVersion='4\&.0' xmlns='http: <ItemGroup><Filter Include='Source Files'><UniqueIdentifier> \fBc\fP"
.br
.ti -1c
.RI "\fBcc\fP"
.br
.ti -1c
.RI "\fBcxx\fP"
.br
.ti -1c
.RI "\fBcppm\fP"
.br
.ti -1c
.RI "\fBixx\fP"
.br
.ti -1c
.RI "\fBdef\fP"
.br
.ti -1c
.RI "\fBodl\fP"
.br
.ti -1c
.RI "\fBidl\fP"
.br
.ti -1c
.RI "\fBhpj\fP"
.br
.ti -1c
.RI "\fBbat\fP"
.br
.ti -1c
.RI "\fBasm\fP"
.br
.ti -1c
.RI "asmx</Extensions ></Filter >< Filter Include='Header Files'>< UniqueIdentifier > \fBhh\fP"
.br
.ti -1c
.RI "\fBhpp\fP"
.br
.ti -1c
.RI "\fBhxx\fP"
.br
.ti -1c
.RI "\fBh\fP"
.br
.ti -1c
.RI "\fBhm\fP"
.br
.ti -1c
.RI "\fBinl\fP"
.br
.ti -1c
.RI "\fBinc\fP"
.br
.ti -1c
.RI "\fBipp\fP"
.br
.ti -1c
.RI "xsd</Extensions ></Filter >< Filter Include='Resource Files'>< UniqueIdentifier > \fBico\fP"
.br
.ti -1c
.RI "\fBcur\fP"
.br
.ti -1c
.RI "\fBbmp\fP"
.br
.ti -1c
.RI "\fBdlg\fP"
.br
.ti -1c
.RI "\fBrc2\fP"
.br
.ti -1c
.RI "\fBrct\fP"
.br
.ti -1c
.RI "\fBbin\fP"
.br
.ti -1c
.RI "\fBrgs\fP"
.br
.ti -1c
.RI "\fBgif\fP"
.br
.ti -1c
.RI "\fBjpg\fP"
.br
.ti -1c
.RI "\fBjpeg\fP"
.br
.ti -1c
.RI "\fBjpe\fP"
.br
.ti -1c
.RI "\fBresx\fP"
.br
.ti -1c
.RI "\fBtiff\fP"
.br
.ti -1c
.RI "\fBtif\fP"
.br
.ti -1c
.RI "\fBpng\fP"
.br
.ti -1c
.RI "\fBwav\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "asm"

.SS "bat"

.SS "bin"

.SS "bmp"

.SS "c"
\fBInitial value:\fP
.PP
.nf
{4FC737F1-C7A5-4376-A066-2A32D752A2FF}</UniqueIdentifier>
      <Extensions>cpp
.fi
.SS "cc"

.SS "cppm"

.SS "cur"

.SS "cxx"

.SS "def"

.SS "dlg"

.SS "gif"

.SS "h"

.SS "asmx</Extensions></Filter><Filter Include='Header Files'><UniqueIdentifier> hh"
\fBInitial value:\fP
.PP
.nf
{93995380-89BD-4b04-88EB-625FBE52EBFB}</UniqueIdentifier>
      <Extensions>h
.fi
.SS "hm"

.SS "hpj"

.SS "hpp"

.SS "hxx"

.SS "xsd</Extensions></Filter><Filter Include='Resource Files'><UniqueIdentifier> ico"
\fBInitial value:\fP
.PP
.nf
{67DA6AB6-F800-4c08-8B7A-83BB121AAD01}</UniqueIdentifier>
      <Extensions>rc
.fi
.SS "idl"

.SS "inc"

.SS "inl"

.SS "ipp"

.SS "ixx"

.SS "jpe"

.SS "jpeg"

.SS "jpg"

.SS "odl"

.SS "png"

.SS "rc2"

.SS "rct"

.SS "resx"

.SS "rgs"

.SS "tif"

.SS "tiff"

.SS "wav"

.SH "Author"
.PP 
Generated automatically by Doxygen for StringUnpacker from the source code\&.
