.TH "Unit" 3 "Mon Dec 27 2021" "StringUnpacker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Unit \- Структура модуль  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <header\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBquantityCurrent\fP"
.br
.RI "количество повторений символа "
.ti -1c
.RI "char \fBChar\fP"
.br
.RI "повторяющаяся буква "
.in -1c
.SH "Detailed Description"
.PP 
Структура модуль 
.SH "Member Data Documentation"
.PP 
.SS "char Unit::Char"

.PP
повторяющаяся буква 
.SS "int Unit::quantityCurrent"

.PP
количество повторений символа 

.SH "Author"
.PP 
Generated automatically by Doxygen for StringUnpacker from the source code\&.
